<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\router\\generator' => '/../src/Generator.php',
                'rapture\\router\\parser' => '/../src/Parser.php',
                'rapture\\router\\route' => '/../src/Route.php',
                'rapture\\router\\router' => '/../src/Router.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
